### ISSUE TITLE
Crossover Grading 12/3

### ISSUE THREAD

**Issue by CalrethilOfMirkwood** [CalrethilOfMirkwood/FOSSite#12]

**Comment by Rebecca-123** [comment]
Grade: 4.75/5
+ Designs look great, located in both issues and wiki
- Technicals - saw 4 or 5 in issues, should probably add a few more ideas
+ Wiki has commit policy
+ Deployment: good description of hardware, maybe add a few notes on frequency
+ Scrum Board - Assignments and Backlog, a few to-do issues showing planning for the future, issues are assigned and have checklists
