### ISSUE TITLE
Week 9 Grading

### ISSUE THREAD

**Issue by CalrethilOfMirkwood** [CalrethilOfMirkwood/FOSSite#35]
## PBL Project Integration:

Sophie got the [terminal fully functional](fe8ad1102632bc32c2e6642bdda7345c48001bba), group is also currently making a "Linux Distro Personality Quiz" that reccomends a Linux distro based on questions.  There is tangible code in progress.

## Create Task Ideas: [link](https://github.com/CalrethilOfMirkwood/FOSSite/wiki/Create-Tasks)

Krish is planning on making High Card while Val and Sophie want to make War.  Both are card games that use dictionaries/lists for card organization and loops for repeated rounds.  There is tangible code in progress.

## 3-Week Plan
Will finalize PBL Quiz next week.  Create task will be finished during the next two weeks.

## Individual College Board Quizzes:
Sophie: ![quiz](https://user-images.githubusercontent.com/82109882/153651566-7b5ed934-bd48-47bd-b45b-6abb41c4ce25.PNG)

**Comment by KrishnadevL** [comment]
## Krish's Week 9 Contribution

### Collegeboard 

**4.3 Quiz**
![image](https://user-images.githubusercontent.com/89166946/153656544-8c4cbe9d-615b-4d6d-aaa9-5070971c51f3.png)

**4.2 Quiz**
![image](https://user-images.githubusercontent.com/89166946/153656613-497e3a41-4c69-4117-a4c5-e6088db57422.png)

**4.1 Quiz**
![image](https://user-images.githubusercontent.com/89166946/153656643-6a408912-3bb8-4d88-b2f6-f9dcd90e5e90.png)
