### ISSUE TITLE
FIGMA Wireframes 

### ISSUE THREAD

**Issue by KrishnadevL** [CalrethilOfMirkwood/FOSSite#5]
- [x] Main Page Wireframe
 - [x] About Linux Page 
 - [ ] CTF Server Landing Page 
 - [ ] Course Landing Page
        - Switching windows to linux
        - Servers + Terminals  
 - [ ] FOSS Alternatives to certain applications 
 - [ ] About Us landing page

**Comment by KrishnadevL** [comment]
- [ ] Main Page Wireframe
 - [ ] About Linux Page 
 - [ ] CTF Server Landing Page 
 - [ ] Course Landing Page
        - [ ]  Switching windows to linux
        - [ ] Servers + Terminals 
        - [ ] 
 - [ ] FOSS Alternatives to certain applications 
 - [ ] About Us landing page

**Comment by michaelScopic** [comment]
figma balls

**Comment by KrishnadevL** [comment]
https://www.figma.com/file/wFSEntAhIZWbk022tdqcOZ/FOS-Site?node-id=12%3A19

**Comment by KrishnadevL** [comment]
Landing Page
![Screenshot 2021-12-02 115738](https://user-images.githubusercontent.com/89166946/144661930-03393349-c9cf-418e-9937-52725c7dc3d7.png)

**Comment by KrishnadevL** [comment]
Tutorial Wiki Page
![Screenshot 2021-12-02 120024](https://user-images.githubusercontent.com/89166946/144661999-6df1ff4c-7f06-4b1b-bca5-072242cb0ced.png)
